
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class BookReceiveView extends javax.swing.JFrame {

    Connection con;
    Statement st;
    ResultSet rs;
        
    String bookIDG;
    
    public BookReceiveView() {
        initComponents();
        connect();
    }
    
    public void connect() {
        try{
            String DRIVER = "sun.jdbc.odbc.JdbcOdbcDriver";
            Class.forName(DRIVER);
            
            String db = "jdbc:odbc:LibraryManagementDatabase";
            con = DriverManager.getConnection(db);
            
            st = con.createStatement();
        } catch(Exception e){
            System.err.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        studentRollSrcTf = new javax.swing.JTextField();
        searchB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        receiveB = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Roll Number");

        studentRollSrcTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentRollSrcTfActionPerformed(evt);
            }
        });

        searchB.setFont(new java.awt.Font("Lithos Pro Regular", 1, 18)); // NOI18N
        searchB.setForeground(new java.awt.Color(0, 0, 255));
        searchB.setText("Search");
        searchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        receiveB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        receiveB.setText("Receive");
        receiveB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                receiveBMouseClicked(evt);
            }
        });
        receiveB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveBActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Lithos Pro Regular", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(studentRollSrcTf, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(searchB, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(receiveB, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentRollSrcTf, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(receiveB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBActionPerformed

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        int count = 0;
        
        String rollT = studentRollSrcTf.getText().toString().trim();

        if (rollT.equals("")) {
            JOptionPane.showMessageDialog(null, "Enter roll number", "Error", JOptionPane.ERROR_MESSAGE, null);
        } else {
            String sql = "SELECT * FROM TransactionTable WHERE StudentRoll LIKE '" + rollT + "' AND IsReturned = No";
            //System.out.println(sql);
            try {
                rs = st.executeQuery(sql);

                //rs to arraylist save
                ArrayList<List<String>> l = new ArrayList<List<String>>();

                while (rs.next()) {
                    count++;
                    l.add(Arrays.asList(rs.getString("BookID")));
                }
                //rs to arraylist finish

                //arraylist to string
                String[][] s = new String[l.size()][];
                for (int i = 0; i < l.size(); i++) {
                    List<String> row = l.get(i);
                    s[i] = row.toArray(new String[row.size()]);
                }
                //arraylist to string array finish                
                
                for (String[] row : s) {
                    model.addRow(row);
                }
                
                if(count == 0) {
                    JOptionPane.showMessageDialog(null, "No book pending");
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(BookReceiveView.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_searchBActionPerformed

    private void receiveBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveBActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int r = jTable1.getSelectedRow();
        if(r < 0) {
            
            if(jTable1.getRowCount() == 0){
                JOptionPane.showMessageDialog(null, "The table is empty.", "Select Book", JOptionPane.ERROR_MESSAGE, null);
                
            } else {
                JOptionPane.showMessageDialog(null, "Select a book", "Select Book", JOptionPane.ERROR_MESSAGE, null);
            }
            
        } else {
            bookIDG = jTable1.getModel().getValueAt(r, 0).toString();
            //System.out.println(bookIDG);
            
            String sqlAv = "UPDATE BookTable SET Availablity = Yes WHERE BookID LIKE '" + bookIDG + "'";
            String sqlRet = "UPDATE TransactionTable SET IsReturned = Yes WHERE BookID LIKE '" + bookIDG + "'";
            
            try {
                st.executeUpdate(sqlAv);
                st.executeUpdate(sqlRet);
                
                model.removeRow(r);
                
                JOptionPane.showMessageDialog(null, "Book received.");
                
            } catch (SQLException ex) {
                Logger.getLogger(BookReceiveView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //if(bookIDG)
    }//GEN-LAST:event_receiveBActionPerformed

    private void receiveBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receiveBMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_receiveBMouseClicked

    private void studentRollSrcTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentRollSrcTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentRollSrcTfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
TransactionWindow obbw = new TransactionWindow();
        obbw.setVisible(true);
        this.dispose();            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookReceiveView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookReceiveView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookReceiveView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookReceiveView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BookReceiveView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton receiveB;
    private javax.swing.JButton searchB;
    private javax.swing.JTextField studentRollSrcTf;
    // End of variables declaration//GEN-END:variables
}
