/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ezio
 */
public class ControlPanel extends javax.swing.JFrame {

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookCornerButton = new javax.swing.JButton();
        studentCornerButton = new javax.swing.JButton();
        aboutUsbutton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(750, 550));
        setMinimumSize(new java.awt.Dimension(750, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookCornerButton.setFont(new java.awt.Font("Lithos Pro Regular", 1, 24)); // NOI18N
        bookCornerButton.setForeground(new java.awt.Color(0, 0, 255));
        bookCornerButton.setText("Books Corner");
        bookCornerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookCornerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(bookCornerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 280, 50));

        studentCornerButton.setFont(new java.awt.Font("Lithos Pro Regular", 1, 24)); // NOI18N
        studentCornerButton.setForeground(new java.awt.Color(0, 0, 255));
        studentCornerButton.setText("Students Corner");
        studentCornerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentCornerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(studentCornerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 280, 50));

        aboutUsbutton.setFont(new java.awt.Font("Lithos Pro Regular", 1, 24)); // NOI18N
        aboutUsbutton.setForeground(new java.awt.Color(0, 0, 255));
        aboutUsbutton.setText("About Us");
        aboutUsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(aboutUsbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 280, 50));

        exitButton.setFont(new java.awt.Font("Lithos Pro Regular", 1, 24)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 453, 100, 40));

        jButton1.setFont(new java.awt.Font("Lithos Pro Regular", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("Transaction ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 280, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library_of_HKUST_2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookCornerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookCornerButtonActionPerformed
       
        BookWindow ob =new BookWindow();
        ob.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_bookCornerButtonActionPerformed

    private void studentCornerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentCornerButtonActionPerformed
        StudentWindow obsw = new StudentWindow();
        obsw.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_studentCornerButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_exitButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      TransactionWindow ob = new TransactionWindow();
        ob.setVisible(true);
        this.dispose();
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aboutUsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsbuttonActionPerformed
 AboutUs obbw = new AboutUs();
        obbw.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_aboutUsbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ControlPanel().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutUsbutton;
    private javax.swing.JButton bookCornerButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton studentCornerButton;
    // End of variables declaration//GEN-END:variables
}
